"""create users table

Revision ID: 03aa82325050
Revises: 
Create Date: 2024-03-15 12:52:35.174749

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03aa82325050"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_engine1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="id"),
        sa.Column("email", sa.String(), nullable=True, comment="メールアドレス"),
        sa.Column("hashed_password", sa.String(), nullable=True, comment="パスワードハッシュ"),
        sa.Column("first_name", sa.String(), nullable=False, comment="名前"),
        sa.Column("last_name", sa.String(), nullable=False, comment="苗字"),
        sa.Column("birthday", sa.Date(), nullable=True, comment="誕生日"),
        sa.Column("is_active", sa.Boolean(), nullable=True, comment="有効フラグ"),
        sa.Column("session_id", sa.String(), nullable=True, comment="セッションID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="作成日時"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新日時"),
        sa.Column("version", sa.BigInteger(), nullable=False, comment="バージョン"),
        sa.PrimaryKeyConstraint("id"),
        comment="ユーザーマスタ",
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade_engine1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def upgrade_engine2() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="id"),
        sa.Column("email", sa.String(), nullable=True, comment="メールアドレス"),
        sa.Column("hashed_password", sa.String(), nullable=True, comment="パスワードハッシュ"),
        sa.Column("first_name", sa.String(), nullable=False, comment="名前"),
        sa.Column("last_name", sa.String(), nullable=False, comment="苗字"),
        sa.Column("birthday", sa.Date(), nullable=True, comment="誕生日"),
        sa.Column("is_active", sa.Boolean(), nullable=True, comment="有効フラグ"),
        sa.Column("session_id", sa.String(), nullable=True, comment="セッションID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="作成日時"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新日時"),
        sa.Column("version", sa.BigInteger(), nullable=False, comment="バージョン"),
        sa.PrimaryKeyConstraint("id"),
        comment="ユーザーマスタ",
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade_engine2() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
