FROM python:3.12.2

WORKDIR /app/fastapi

ENV PYTHONPATH "/app/fastapi:$PYTHONPATH"

COPY ./fastapi /app/fastapi

RUN pip install --no-cache-dir --upgrade -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
